Update updatesystem

diff --git a/bin/updatesystem b/bin/updatesystem
--- a/bin/updatesystem
+++ b/bin/updatesystem
@@ -288,7 +288,16 @@ if [[ $PacOff == "No" ]]; then
   echo
   echo -e $blue"===>$reset Checking for pacnew files..."
   echo
-  { $SUDO find /etc -regextype posix-extended -regex ".+\.pac(new|save)" 2> /dev/null ; } && { echo ; echo "No pacnew file found" ; } || { echo ; echo -e $red"Error:$reset Pacnew file(s) found! (Use pacdiff to deal with them)" ; exit 1; }
+  if [[ $($SUDO find /etc -regextype posix-extended -regex ".+\.pac(new|save)" 2> /dev/null) ]]; then
+  	echo -e $red"Error:$reset Pacnew file(s) found! (Use pacdiff to deal with them):"
+        echo
+        $SUDO find /etc -regextype posix-extended -regex ".+\.pac(new|save)" 2> /dev/null
+        echo
+        exit 1
+  else
+        echo 
+        echo "No pacnew file found"
+  fi
   echo
   echo
 fi
