Update update-arch

diff --git a/bin/update-arch b/bin/update-arch
--- a/bin/update-arch
+++ b/bin/update-arch
@@ -14,6 +14,7 @@ Args=$@
 USERNAME=${SUDO_USER:-$(id -u -n)}
 HOMEDIR="/home/$USERNAME"
 SUDO=""
+
 if [ $EUID -ne 0 ]; then
     SUDO='/usr/bin/sudo'
 fi
@@ -44,7 +45,7 @@ UpdateMirrorCMD="${SUDO} /usr/bin/reflector --sort rate --latest 10 --protocol h
 SuspendCMD="/usr/bin/systemctl suspend"
 ShutdownCMD="/usr/bin/systemctl poweroff"
 RebootCMD="/usr/bin/systemctl reboot"
-LogoutCMD="/usr/bin/loginctl terminate-user $USERNAME"
+LogoutCMD="$HOMEDIR/bin/logoff"
 HibernateCMD="/usr/bin/systemctl hibernate"
 
 function help {
@@ -421,7 +422,7 @@ if [[ $Tmux == "Yes" ]]; then
                 Arguments="${Arguments}y"
             fi
             if [[ $LoggingOff == "Yes" ]]; then
-                Arguments = "${Arguments}l"
+                Arguments="${Arguments}l"
             fi
             if [[ $RSSOff == "Yes" ]]; then
                 Arguments="${Arguments}r"
@@ -535,7 +536,7 @@ if [[ $Install == "Yes" ]] || [[ $Build == "Yes" ]]; then
         echo ""
         echo -e $blue"===>$reset Checking the build package file for error..."
         echo ""
-        /usr/bin/find . -maxdepth 1 -name '*.pkg.tar.xz' -exec /usr/bin/namcap {} \;
+	/usr/bin/find . -maxdepth 1 \( -name '*.pkg.tar.xz' -o -name '*.pkg.tar.zst' \) -exec /usr/bin/namcap {} \;
         echo ""
         read -p "Press enter to continue..."
     fi
@@ -543,7 +544,7 @@ if [[ $Install == "Yes" ]] || [[ $Build == "Yes" ]]; then
         echo ""
         echo -e $blue"===>$reset Installing the package..."
         echo ""
-        { /usr/bin/find . -maxdepth 1 -name '*.pkg.tar.xz' -exec $SUDO /usr/bin/pacman -U {} \; ; } || { echo "" ; echo -e $red"Error:$reset Cannot install the package" ; exit 1; }
+	{ /usr/bin/find . -maxdepth 1 \( -name '*.pkg.tar.xz' -o -name '*.pkg.tar.zst' \) -exec $SUDO /usr/bin/pacman -U {} \; ; } || { echo "" ; echo -e $red"Error:$reset Cannot install the package" ; exit 1; }
     fi
 fi
 if [[ $Sync == "Yes" ]]; then
@@ -552,7 +553,11 @@ if [[ $Sync == "Yes" ]]; then
 	echo
 	if [[ ! $Refresh == "Yes" ]]; then
 	  if [[ $AUR == "Yes" ]]; then
-	    if [ -x /usr/bin/yaourt ]; then
+	    if [ -x /usr/bin/yay ]; then
+            { /usr/bin/sudo -u $USERNAME /usr/bin/yay -Syu ; } || { echo -e $red"Error:$reset Cannot update the system" ; exit 1; }
+	    elif [ -x /usr/bin/trizen ]; then
+            { /usr/bin/sudo -u $USERNAME /usr/bin/trizen -Syu ; } || { echo -e $red"Error:$reset Cannot update the system" ; exit 1; }
+	    elif [ -x /usr/bin/yaourt ]; then
             { /usr/bin/sudo -u $USERNAME /usr/bin/yaourt -Syua ; } || { echo -e $red"Error:$reset Cannot update the system" ; exit 1; }
         else
             echo -e $red"Error:$reset Yaourt not found"
@@ -565,7 +570,11 @@ if [[ $Sync == "Yes" ]]; then
       fi
     else
       if [[ $AUR == "Yes" ]]; then
-        if [ -x /usr/bin/yaourt ]; then
+        if [ -x /usr/bin/yay ]; then
+            { /usr/bin/sudo -u $USERNAME /usr/bin/yay -Syyu ; } || { echo -e $red"Error:$reset Cannot update the system" ; exit 1; }
+        elif [ -x /usr/bin/trizen ]; then
+            { /usr/bin/sudo -u $USERNAME /usr/bin/trizen -Syyu ; } || { echo -e $red"Error:$reset Cannot update the system" ; exit 1; }
+        elif [ -x /usr/bin/yaourt ]; then
             { /usr/bin/sudo -u $USERNAME /usr/bin/yaourt -Syyua ; } || { echo -e $red"Error:$reset Cannot update the system" ; exit 1; }
         else
             echo -e $red"Error:$reset Yaourt not found"
@@ -617,7 +626,7 @@ elif [[ $Shutdown == "Yes" ]]; then
      sleep 1s
      clear
      echo -e $red"Shutdown$reset in$green $x$reset seconds..."
-     x=$(( $x - 1 ))
+     x=$(( x - 1 ))
   done
   eval "${ShutdownCMD}"
 elif [[ $Reboot == "Yes" ]]; then
